language : node_js

node_js:
  - 12

install:
  - npm ci

script:
  - npm install --dev
  - npm start

deploy:
  provider: heroku
  api_key: 
    secure: 56db2e91-c8da-4db5-b4e3-51d82165119e
  app: spacex-launch-program-ssr
  on:
    repo: poonam-stack/spacex-launch-program-ssr